services:
  robot_sim:
    build: .
    image: mobile_robot_sim:latest
    container_name: mobile_robot_container
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY=:1
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - GAZEBO_IP=127.0.0.1
      - GAZEBO_MASTER_URI=http://localhost:11345
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/Assistive_robot/src   # ← mount src/ to src/ not whole project
    stdin_open: true
    tty: true