controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Your new custom controller (Single entry for the whole robot)
    omni_base_controller:
      type: pid_controller/PidController


omni_base_controller:
  ros__parameters:
    # Physical Robot Constants (from your Schema)
    robot_radius: 0.15
    wheel_radius: 0.05
    num_of_wheels: 3
    i_min: -5.0
    i_max: 5.0

    # PID Gains for each wheel (Matches your Schema structure)
    wheel_1:
      kp: 10.0
      ki: 0.1
      kd: 0.01
    
    wheel_2:
      kp: 10.0
      ki: 0.1
      kd: 0.01

    wheel_3:
      kp: 10.0
      ki: 0.1
      kd: 0.01