controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    omni_base_controller:
      type: omni_pid_controller/PidController

omni_base_controller:
  ros__parameters:
    dof_names:
      - mobile_base_Revolute_1
      - mobile_base_Revolute_2
      - mobile_base_Revolute_3
    command_interface: effort        
    reference_and_state_interfaces:
      - velocity
    robot_radius: 0.13
    wheel_radius: 0.06
    num_of_wheels: 3
    i_min: -5.0
    i_max: 5.0
    wheel_1:
      kp: 0.1
      ki: 0.1
      kd: 0.01
    wheel_2:
      kp: 0.1
      ki: 0.1
      kd: 0.01
    wheel_3:
      kp: 0.1
      ki: 0.1
      kd: 0.01
