ekf_estimator:
  robot_dimensions:
    wheel_radius: { type: double, default_value: 0.02525, description: "รัศมีล้อหุ่นยนต์ (เมตร)" }
    robot_length: { type: double, default_value: 0.217, description: "ระยะทางห่างจากจุดศูนย์กลางถึงล้อตามแนวแกน X" }
    robot_width: { type: double, default_value: 0.211, description: "ระยะทางห่างจากจุดศูนย์กลางถึงล้อตามแนวแกน Y" }
  ekf_tuning:
    process_noise_theta:    {type: double, default_value: 0.02,    description: "ค่าคอยน์แวเรียนซ์ของโมเดล (Q)"}
    measurement_noise_gyro: {type: double, default_value: 0.0001,  description: "ค่าความแปรปรวนสัญญาณรบกวนของ IMU Gyro (R1)"}
  odom_topic:    {type: string, default_value: "/ekf_estimate/odom"}
  odom_frame_id: {type: string, default_value: "/ekf_estimate/odom"}
  base_frame_id: {type: string, default_value: "base_footprint"}